name: CI

on:
  push:
  pull_request:

jobs:
  backend:
    name: Backend (Laravel)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, intl, pdo_sqlite, json, curl
          tools: composer:v2
          coverage: none

      - name: Cache composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install deps
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: App key & env
        run: |
          cp .env.example .env || true
          php artisan key:generate
      - name: Seed fixtures for tests
        run: |
          mkdir -p storage/app/private/fixtures/default
          mkdir -p storage/app/private/fixtures/raining
          if [ -d tests/Fixtures ]; then
            cp -R tests/Fixtures/default/* storage/app/private/fixtures/default/
            cp -R tests/Fixtures/raining/* storage/app/private/fixtures/raining/
          fi

      - name: Lint (Pint)
        run: composer lint

      - name: Test (Pest)
        run: composer test

  frontend:
    name: Frontend (ui)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: ui/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Lint (ESLint + Prettier)
        run: |
          npm run lint
          npx prettier --check . --ignore-path .gitignore
      - name: Tests (if present)
        run: npm test --if-present
